### ISSUE TITLE
Performance/Memory issues with more than 60K records

### ISSUE THREAD

**Issue by SapneshNaik** [primetwig/react-nestable#106]
Hi,

I am trying to render a tree with around 60K items, and I see that the whole page lags and the memory consumption (Heap size) is over 800MB. Is this expected? Is it possible to lazy load the tree to mitigate this issue?

**Comment by primetwig** [comment]
it is not optimized for big data. even if I render placeholders with viewport observer or calculate visible items based on amount of pixels scrolled (while trying not to introduce bugs because of dynamic height of items)... there are still some things under the hood which use a full list walkthrough for some checks.

having that in mind, I would suggest using a custom solution for your case.
feel free to snatch any pieces of code that you find useful.
